# default.yaml
# Specifies the upper and lower limits of UR5 joints in the urdf.
#
# In theory all joints support 2.0 * pi = 6.2831853, but
# elbow_joint AND wrist_2_joint are restricted to +/-pi as they
# cannot leave this range without guaranteed self-collision of the robot
#
# Additionally states close to the joint's physical limits
# can trigger protective stops in the UR controller.
# To prevent that we subtract a safety margin of 0.002.

shoulder_pan_joint:
    lower: -2.7
    upper: 2.7
shoulder_lift_joint:
    lower: -3.3
    upper: 0.2
elbow_joint:
    lower: -3.1415926
    upper: 3.1415926
wrist_1_joint:
    lower: -6.2811853
    upper: 6.2811853
wrist_2_joint:
    lower: -3.1415926
    upper: 3.1415926
wrist_3_joint:
    lower: -6.2811853
    upper: 6.2811853
